### ISSUE TITLE
每次放大或缩小时会有延迟。

### ISSUE THREAD

**Issue by xingwujie** [ZemingLun/CesiumHeatmap#1]
每次放大或缩小时会有延迟。是因为生成热力图时间太长阻塞了系统的运行么？是否应该改成异步的。

**Comment by ZemingLun** [comment]
是的，可以选择监听camera停止移动事件会比监听鼠标滚动事件好
viewer.scene.camera.moveEnd.addEventListener(function(){

})；

**Comment by ZemingLun** [comment]
> 每次放大或缩小时会有延迟。是因为生成热力图时间太长阻塞了系统的运行么？是否应该改成
